---
title: "Slot Machine Choice"
output: html_notebook
---

#quality check
```{r}
dataset <- batch3_cumulative
datadir = "/Users/Ella/Desktop/SURF/data"
library(dplyr)

# Check 1: Positive slope in psychometric curve for each participant
check1 <- dataset %>%
  filter(`Screen Name` == "stim 1") %>%
  group_by(`Participant Private ID`, s, Response) %>%
  summarise(count = n()) %>%
  mutate(total = sum(count),
         percent = count / total) %>%
  filter(Response == "YES") %>%
  arrange(`Participant Private ID`, s) %>%
  group_by(`Participant Private ID`) %>%
  mutate(slope_check = all(diff(percent) > 0)) %>%
  summarise(slope_check = all(slope_check))

# Check 2: Participants with at least 90% response rate
check2 <- dataset %>%
  filter(`Zone Type` %in% c("force_advance", "response_keyboard_single")) %>%
  group_by(`Participant Private ID`) %>%
  summarise(total_count = n(),
            response_single_count = sum(`Zone Type` == "response_keyboard_single"),
            response_rate = response_single_count / total_count) %>%
  mutate(response_rate_check = response_rate >= 0.9)

# Check 3: Average response time greater than 350ms
check3 <- dataset %>%
  filter(`Screen Name` == "stim 1") %>%
  group_by(`Participant Private ID`) %>%
  summarise(avg_reaction_time = mean(`Reaction Time`)) %>%
  mutate(reaction_time_check = avg_reaction_time > 350)

# View the results
QC <- check1
QC$response_rate <- check2$response_rate
QC$response_rate_check <- check2$response_rate_check
QC$avg_RT <- check3$avg_reaction_time
QC$RT_check <- check3$reaction_time_check

QC

# Print participant IDs of people who fail any of the three checks
failed_checks <- unique(c(
  ifelse(check1$slope_check == FALSE, check1$`Participant Private ID`, NA),
  ifelse(check2$response_rate_check == FALSE, check2$`Participant Private ID`, NA),
  ifelse(check3$reaction_time_check == FALSE, check3$`Participant Private ID`, NA)
))

failed_checks <- failed_checks[!is.na(failed_checks)]

if (length(failed_checks) > 0) {
  print(paste0("Participant IDs who failed the checks: ", paste(failed_checks, collapse = ", ")))
} else {
  print("All participants passed the checks.")
}

# Create a new dataset called "good" with participants who failed the checks
good <- dataset %>%
  filter(!(`Participant Private ID` %in% failed_checks))

# Save the dataset as a CSV file in the specified folder
file_path <- file.path(datadir, "data.csv")
write.csv(good, file = file_path, row.names = FALSE)

exploratory_participants <- c(9040278, 9040291, 9061286, 9061240, 9061317, 9061321, 9061334, 9061380, 9061385, 9061386, 9061368, 9061388, 9061402, 9061404, 9061396, 9061394, 9061416, 9061429, 9061439, 9061450, 9061599, 9062131, 9040255, 9040290, 9040277)

exploratory <- good %>%
  filter(`Participant Private ID` %in% exploratory_participants)
file_path <- file.path(datadir, "exploratory.csv")
write.csv(exploratory, file = file_path, row.names = FALSE)

confirmatory <- good %>%
  filter(!(`Participant Private ID` %in% exploratory_participants))
file_path <- file.path(datadir, "confirmatory.csv")
write.csv(confirmatory, file = file_path, row.names = FALSE)

confirmatory_unique_count <- confirmatory %>%
  distinct(`Participant Private ID`) %>%
  n_distinct()

print(confirmatory_unique_count)

```
#creating preliminary data
```{r}
library(dplyr)

pdata <- exploratory[exploratory$`Screen Name` == "stim 1" & !is.na(exploratory$`Participant Private ID`), ] %>%
  group_by(`Participant Private ID`, s) %>%
  summarize(
    percent.choice = mean(Correct),
    se_percent.choice = sd(Correct) / sqrt(n()),
    avg_rxn = mean(`Reaction Time`),
    se_avg_rxn = sd(`Reaction Time`) / sqrt(n()),
    avg_machine_val = mean(sapply(e, function(x) {
      vals <- as.numeric(strsplit(gsub("[c\\(\\)]", "", x), ", ")[[1]])
      mean(vals)
    })),
    se_avg_machine_val = sd(sapply(e, function(x) {
      vals <- as.numeric(strsplit(gsub("[c\\(\\)]", "", x), ", ")[[1]])
      mean(vals)
    })) / sqrt(n())
  )

pdata <- pdata[-126, ]

# Rename columns
colnames(pdata)[1:2] <- c("subj", "machines")

# Update subj column with unique numeric values starting from 1
pdata$subj <- factor(pdata$subj, levels = unique(pdata$subj[!is.na(pdata$subj)]), labels = seq_along(unique(pdata$subj[!is.na(pdata$subj)])))


pdata$machines <- pdata$machines - 3

#Compile machine_data
machine_data <- pdata %>%
  group_by(machines) %>%
  summarize(
    machine_mean = mean(avg_rxn),
    se_machine_mean = sd(avg_rxn) / sqrt(n()),
    percent_choice = mean(percent.choice),
    se_percent_choice = sd(percent.choice) / sqrt(n()))

```
#analysis data
```{r}
library(dplyr)
datadir = "/Users/Ella/Desktop/SURF/data"

#adata
threshold <- 100
adata <- exploratory %>%
  filter(`Screen Name` == "stim 1" & !is.na(`Participant Private ID`)) %>%
  select(`Participant Private ID`, `Trial Number`, Response, `Reaction Time`, s, e, size, color) %>%
  group_by(`Participant Private ID`, s, `Reaction Time`) %>%
  mutate(
    StimuliSeen = ifelse((`Reaction Time` / 300) %% 1 >= threshold, ceiling(`Reaction Time` / 300), floor(`Reaction Time` / 300))
  )

# Rename columns
colnames(adata)[1:5] <- c("subj", "trial", "choice", "rxn_time", "machine")

# Update subj column with unique numeric values starting from 1
adata$subj <- factor(adata$subj, levels = unique(adata$subj[!is.na(adata$subj)]), labels = seq_along(unique(adata$subj[!is.na(adata$subj)])))

# Remove practice trials
adata <- adata %>%
  group_by(subj) %>%
  slice(-(1:10)) %>%
  ungroup()

# Subtract 10 from Trial Number
adata$trial <- as.numeric(as.character(adata$trial))
adata$trial <- adata$trial - 10

# Change machine values to their means
adata$machine <- as.numeric(as.character(adata$machine))
adata$machine <- adata$machine - 3

# Initialize stim column as NA
adata$stim <- adata$e


adata <- adata %>%
  rowwise() %>%
  mutate(
    stim = paste(unlist(strsplit(substr(stim, 3, nchar(stim)), ", "))[1:StimuliSeen], collapse = ", ")
  ) %>%
  ungroup()

#lookup table for stim 
lookup_table <- data.frame(
  lower_bound = c(-Inf, -2.75, -2.5, -2.25, -2, -1.75, -1.5, -1.25, -1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 2.75),
  upper_bound = c(-2.75, -2.5, -2.25, -2, -1.75, -1.5, -1.25, -1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 2.75, Inf),
  stimulus = c(-2.875, -2.625, -2.375, -2.125, -1.875, -1.625, -1.375, -1.125, -0.875, -0.625, -0.375, -0.125, 0.125, 0.375, 0.625, 0.875, 1.125, 1.375, 1.625, 1.875, 2.125, 2.375, 2.625, 2.875))

# Loop over each row in the data frame
for (i in 1:nrow(adata)) {
  # Split the existing "stim" value into separate elements
  stim_values <- unlist(strsplit(substr(adata$stim[i], 3, nchar(adata$stim[i])), ", "))
  
  # Find the matching stimuli based on the "stim" values
  updated_stimuli <- character(length(stim_values))
  for (j in 1:length(stim_values)) {
    stim_value <- as.numeric(stim_values[j])
    stim_index <- findInterval(stim_value, lookup_table$lower_bound)
    updated_stimuli[j] <- as.character(lookup_table$stim[stim_index])
  }
  
  # Combine the updated stimuli into a single string and assign it to the "stim" column
  adata$stim[i] <- paste(updated_stimuli, collapse = ", ")
}

adata <- adata %>%
  select(-e, -size, -color)

# Remove rows where "choice" column is equal to "NA"
adata <- adata[!is.na(adata$choice), ]


library(tidyr)
adata_long <- adata %>%
  separate_rows(stim, sep = ", ") %>%
  mutate(stim = as.numeric(stim))

adata_long <- adata_long %>%
  group_by(subj, trial) %>%
  mutate(
    S0 = last(stim),
    S1 = ifelse(length(stim) > 1, stim[length(stim) - 1], NA),
    S2 = ifelse(length(stim) > 2, stim[length(stim) - 2], NA),
    Selse = ifelse(length(stim) > 3, mean(stim[1:(length(stim) - 3)]), NA)
  ) %>%
  ungroup()

file_path <- file.path(datadir, "SlotMachineChoice_data.csv")
write.csv(adata_long, file = file_path, row.names = FALSE)

adata$S0 <- adata_long$S0[match(adata$trial, adata_long$trial)]
adata$S1 <- adata_long$S1[match(adata$trial, adata_long$trial)]
adata$S2 <- adata_long$S2[match(adata$trial, adata_long$trial)]
adata$Selse <- adata_long$Selse[match(adata$trial, adata_long$trial)]


```

#adata for YES/NO density plot
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)

adata_density <- adata %>%
  pivot_longer(cols = c(S0, S1, S2, Selse), names_to = "sig_type", values_to = "sig_val") %>%
  group_by(across(-c(sig_type, sig_val))) %>%
  fill(everything(), .direction = "down") %>%
  ungroup()

adata_density$sig_type = factor(adata_density$sig_type, levels = c("S0", "S1", "S2", "Selse"), labels = c("S0", "S1", "S2", "Selse"))

yn_density <- ggplot(data = adata_density, aes(x = sig_val)) +
  geom_vline(aes(xintercept = 0), alpha = 0.25) +
  geom_hline(aes(yintercept = 0.15), alpha = 0.25) +
  geom_density(alpha = 0.5, na.rm = TRUE) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  coord_cartesian(expand = FALSE) +
  labs(
    title = "Influence of Signal Value on Yes Decisions At Different Points 
in the Trial",
    x = "Signal Value",
    y = "Proportion",
    fill = "Signal Type") +
  facet_grid(cols = vars(choice), rows = vars(sig_type)) +
  theme(panel.spacing = unit(1, "lines"))
yn_density

```
#adata for AVG SIGNAL PlOT
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)

adata_long_graph <- adata_long %>%
  select(subj, trial, choice, rxn_time, machine, StimuliSeen, stim) %>%
  group_by(subj, trial) %>%
  mutate(
    time = row_number(),
    avg_sig_raw = cummean(stim),
    avg_sig_all = mean(stim)) %>%
  complete(time = (1:40), fill = list(NA)) %>%
  fill(choice) %>%
  fill(rxn_time) %>%
  fill(machine) %>%
  fill(StimuliSeen) %>%
  fill(stim) %>%
  fill(avg_sig_raw) %>%
  fill(avg_sig_all) %>%
  mutate(
    time = (time*300)/1000,
    choice = ifelse(row_number() <= (StimuliSeen - 1), "UND", choice)) %>%
  ungroup()

# Lookup table for avg_sig
lookup_table <- data.frame(
  lower_bound = c(-Inf, -3.5, -2.5, -1.5, -0.5, 0.5, 1.5, 2.5, 3.5),
  upper_bound = c(-3.5, -2.5, -1.5, -0.5, 0.5, 1.5, 2.5, 3.5, Inf),
  stimulus = c(-4, -3, -2, -1, 0, 1, 2, 3, 4)
)

adata_long_graph <- adata_long_graph %>%
  mutate(avg_sig = cut(avg_sig_all, breaks = c(lookup_table$lower_bound, Inf), labels = lookup_table$stimulus, include.lowest = TRUE))

adata_long_yes <- adata_long_graph %>%
  group_by(subj, avg_sig, time) %>%
  mutate(
    percent_ind = mean(choice == "YES" & choice != "UND" & choice != "NO")) %>%
  ungroup()

adata_long_yes <- adata_long_yes %>%
  group_by(avg_sig, time) %>%
  mutate(
    percent_choice = mean(percent_ind)) %>%
  ungroup()
  
avg_sig_yes <- ggplot(data = adata_long_yes, aes(x = time, y = percent_choice, group = avg_sig)) +
  geom_line(linewidth=2, aes(color = as.factor(avg_sig))) +
  labs(title = "How Often Participants Chose to Play Over Time Based on the 
       Average Stimulus They Saw",
       y = "% Time YES Chosen", 
       x = "Time (seconds)",
       color = "Average Stimulus") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  coord_cartesian(expand = F) +
  guides(fill = "none") +
  guides(color = guide_legend(reverse = TRUE)) +
  theme(legend.position = "right")
avg_sig_yes

adata_long_no <- adata_long_graph %>%
  group_by(subj, avg_sig, time) %>%
  mutate(
    percent_ind = mean(choice == "NO" & choice != "UND" & choice != "YES")) %>%
  ungroup()

adata_long_no <- adata_long_no %>%
  group_by(avg_sig, time) %>%
  mutate(
    percent_choice = mean(percent_ind)) %>%
  ungroup()
  
avg_sig_no <- ggplot(data = adata_long_no, aes(x = time, y = percent_choice, group = avg_sig)) +
  geom_line(linewidth=2, aes(color = as.factor(avg_sig))) +
  labs(title = "How Often Participants Chose Not to Play Over Time Based on the 
       Average Stimulus They Saw",
       y = "% Time YES Chosen", 
       x = "Time (seconds)",
       color = "Average Stimulus") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  coord_cartesian(expand = F) +
  guides(fill = "none") +
  guides(color = guide_legend(reverse = FALSE)) +
  theme(legend.position = "right")
avg_sig_no
  
```


#basic data plots
```{r}
library(ggplot2)

figdir = "/Users/Ella/Desktop/SURF/figures"
fig_height = 4
fig_width = 6

#x = SM, y = %chosen
p.choice <- ggplot(data = pdata, aes(x = machines, y = percent.choice, group = subj)) +
  geom_line(linewidth=2, aes(color = as.factor(subj))) +
  geom_ribbon(aes(ymin = percent.choice - se_percent.choice, ymax = percent.choice + se_percent.choice, fill = subj), 
              alpha = 2.5/10) +
  labs(title = "How Often Individual Participants Chose to Play Each Machine",
       y = "% Time YES Chosen", 
       x = "Average Machine Payout",
       color = "Participants") +
  theme_bw() +
  coord_cartesian(expand = F) +
  guides(fill = "none") +
  theme(legend.position = "right")
p.choice

#mean
p.machine_choice <- ggplot(data = machine_data, aes(x = machines, y = percent_choice)) +
  geom_hline(aes(yintercept = 0.5), alpha = 0.25) +
  geom_vline(aes(xintercept = 0), alpha = 0.25) +
  geom_line(color = "green", linewidth = 2) +
  geom_ribbon(aes(ymin = percent_choice - se_percent_choice, ymax = percent_choice + se_percent_choice), 
              fill = "green", alpha = 2.5/10) +
  labs(title = "How Often Participants Chose to Play Each Machine On Average",
       y = "% of Time YES Chosen", 
       x = "Average Machine Payout") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ylim(0,1) +
  coord_cartesian(expand = FALSE) +
  guides(fill = "none")
p.machine_choice

#x = SM, y = RT
p.RT <- ggplot(data = pdata, aes(x = machines, y = avg_rxn, group = subj)) +
  geom_ribbon(aes(ymin = avg_rxn - se_avg_rxn, ymax = avg_rxn + se_avg_rxn, fill = subj), alpha = 2.5/10) +
  geom_line(linewidth=2, aes(color = subj)) +
  labs(title = "Individual Participant Reaction Time for Each Machine",
       y = "Average Reaction Time (ms)", 
       x = "Average Machine Payout",
       color = "Participants") +
  theme_bw() +
  coord_cartesian(expand = F) +
  guides(fill = "none") +
  theme(legend.position = "right")
p.RT

#mean
p.machine_RT <- ggplot(data = machine_data, aes(x = machines, y = machine_mean)) +
  geom_vline(aes(xintercept = 0), alpha = 0.25) +
  geom_line(color = "blue", size = 2) +
  geom_ribbon(aes(ymin = machine_mean - se_machine_mean, ymax = machine_mean + se_machine_mean), 
              fill = "blue", alpha = 0.25) +
  labs(title = "Average Participant Reaction Time for Each Machine",
       y = "Average Percent Choice", 
       x = "Average Machine Payout") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ylim(0, 3500) +
  coord_cartesian(expand = FALSE) +
  guides(fill = "none")
p.machine_RT

#x = avg machine value, y = percent choice
p.avg_stim <- ggplot(data = pdata, aes(x = avg_machine_val, y = percent.choice, group = subj)) +
  geom_line(color = "purple", linewidth = 2) +
  geom_ribbon(aes(ymin = percent.choice - se_percent.choice, ymax = percent.choice + se_percent.choice), 
              fill = "purple", alpha = 2.5/10) +
  labs(title = "How Often Participants Chose to Play Based on Average Machine Payout",
       y = "% Time YES Chosen", 
       x = "Average Machine Payout") +
  theme_bw() +
  coord_cartesian(expand = F) +
  guides(fill = "none") +
  theme(legend.position = "right")
p.avg_stim

```

#save graphs
```{r}
figdir = "/Users/Ella/Desktop/SURF/figures"
fig_height = 4
fig_width = 6

ggsave(file.path(figdir, "p.RT.pdf"), plot = p.RT, 
       width = fig_width, height = fig_height, units = "in")

ggsave(file.path(figdir, "p.choice.pdf"), plot = p.choice, 
       width = fig_width, height = fig_height, units = "in")

ggsave(file.path(figdir, "p.machine_RT.pdf"), plot = p.machine_RT, 
       width = fig_width, height = fig_height, units = "in")

ggsave(file.path(figdir, "p.machine_choice.pdf"), plot = p.machine_choice, 
       width = fig_width, height = fig_height, units = "in")

ggsave(file.path(figdir, "p.avg_stim.pdf"), plot = p.avg_stim, 
       width = fig_width, height = fig_height, units = "in")

ggsave(file.path(figdir, "yn_density.pdf"), plot = yn_density, 
       width = fig_width, height = fig_height, units = "in")

ggsave(file.path(figdir, "avg_sig_plot.pdf"), plot = avg_sig_plot, 
       width = fig_width, height = fig_height, units = "in")
```


#extra
```{r}
p.pilot.machine_choice <- ggplot(data = machine_data, aes(x = machines, y = percent_choice)) +
  geom_bar(stat = "identity", aes(fill = machines)) +
  geom_text(aes(label = paste0(round(percent_choice*100, 1), "%"), vjust = 2)) +
  labs(title = "How Often Participants Chose to Play Each Machine On Average",
       y = "% of Time YES Chosen", 
       x = "Average Machine Payout") +
  theme_bw() +
  coord_cartesian(expand = F) +
  guides(fill = "none")
p.pilot.machine_choice

p.pilot.machine_RT <- ggplot(data = machine_data, aes(x = machines, y = machine_mean)) +
  geom_bar(stat = "identity", aes(fill = machines)) +
  geom_text(aes(label = paste0(round(machine_mean), " ms"), vjust = 2)) +
  labs(title = "Average Participant Reaction Time for Each Machine",
       y = "Average Reaction Time (ms)", 
       x = "Average Machine Payout") +
  theme_bw() +
  coord_cartesian(expand = F) +
  guides(fill = "none")
p.pilot.machine_RT

p.pilot.machine_RT <- ggplot(data = machine_data, aes(x = machines, y = machine_mean)) +
  geom_line(color = "blue", size = 2, group = 1) +
  geom_ribbon(aes(ymin = machine_mean - se_machine_mean, ymax = machine_mean + se_machine_mean, fill = "machines"), 
              alpha = 0.75) +
  geom_errorbar(aes(ymin = machine_mean - se_machine_mean, ymax = machine_mean + se_machine_mean),
                width = 0.2, color = "blue", size = 1) +
  labs(title = "Average Machine Payout",
       y = "Average Percent Choice", 
       x = "Average Machine Payout") +
  theme_bw() +
  coord_cartesian(expand = FALSE) 
  #guides(fill = "none")

p.pilot.machine_RT


#linear regression

library(ggplot2)

lmChoice = lm(percent.choice~machines, data = pdata) #Create the linear regression
summary(lmChoice)
ggplot(data = pdata, aes(x = machines, y = percent.choice)) +
  geom_point(color = "blue") +
  geom_abline(intercept = lmChoice$coefficients[1], slope = lmChoice$coefficients[2]) +
  labs(x = "Machines", y = "Percent Choice") # Add labels to axes
plot(lmChoice$residuals, pch = 16, col = "red")

lmStim = lm(percent.choice~avg_machine_val, data = pdata) #Create the linear regression
summary(lmChoice)
ggplot(data = pdata, aes(x = avg_machine_val, y = percent.choice)) +
  geom_point(color = "purple") +
  geom_abline(intercept = lmStim$coefficients[1], slope = lmStim$coefficients[2]) +
  labs(x = "Average Machine Payout", y = "Percent Choice") # Add labels to axes
plot(lmChoice$residuals, pch = 16, col = "orange")
```

